import json
from pathlib import Path
root=Path(__file__).resolve().parents[1]
modules=[
 dict(id='foundations',number=1,title='Первый контакт',description='Функции, типы и решения. Без перегруза.'),
 dict(id='ownership',number=2,title='Кому принадлежат данные',description='Ownership и borrowing на маленьких примерах.'),
 dict(id='collections',number=3,title='Данные и ошибки',description='Коллекции, Option, Result и итераторы.'),
 dict(id='design',number=4,title='Думать как Rust-разработчик',description='Структуры, enums, traits и композиция.')]
lessons=[]
def add(id,module,title,summary,heading,text,example,task,starter,solution,assertions,hints,labels,minutes=8):
    tests='\n'.join(f'    #[test]\n    fn case_{i}() {{ {a} }}' for i,a in enumerate(assertions,1))
    lessons.append(dict(id=id,module=module,title=title,summary=summary,minutes=minutes,xp=50,theory=[dict(heading=heading,text=text,example=example),dict(heading='Как пройти уровень',text='Прочитайте условие, измените функцию в редакторе и нажмите «Проверить код». Компилятор проверит типы, а тесты — поведение. Ошибка не отнимает опыт. Подсказки открываются постепенно.',example=None)],task=task,starter=starter,solution=solution,tests='#[cfg(test)]\nmod rustpath_tests {\n    use super::*;\n'+tests+'\n}',hints=hints,test_labels=labels))
add('hello','foundations','Привет, Rust!','Первая функция и первое маленькое достижение.','Функция возвращает значение','fn объявляет функцию, а -> задаёт тип результата. &\'static str — ссылка на строковый литерал, который живёт всё время работы программы. Последнее выражение без точки с запятой становится результатом функции. Подробно время жизни изучим позже.','pub fn language() -> &\'static str {\n    "Rust"\n}','Верните из greeting точную строку «Привет, Rust!». Не меняйте сигнатуру функции.','pub fn greeting() -> &\'static str {\n    "Привет, мир!"\n}','pub fn greeting() -> &\'static str { "Привет, Rust!" }',['assert_eq!(greeting(), "Привет, Rust!");'],['Измените только строку внутри кавычек.','Нужна точная строка «Привет, Rust!», включая запятую и восклицательный знак.'],['Точное приветствие'],5)
add('arithmetic','foundations','Числа работают на вас','Типы и арифметика без магии.','Числовые типы','i32 — знаковое 32-битное число. Аргументы функции имеют имена и типы. Арифметика работает как обычно, но тип результата должен совпадать с объявленным. Условия задания задают безопасный диапазон без переполнения.','pub fn double(x: i32) -> i32 {\n    x * 2\n}','Реализуйте sum: сумму a и b. Входные значения находятся в диапазоне от -1000 до 1000.','pub fn sum(a: i32, b: i32) -> i32 {\n    0\n}','pub fn sum(a: i32, b: i32) -> i32 { a + b }',['assert_eq!(sum(2, 3), 5);','assert_eq!(sum(-8, 3), -5);','assert_eq!(sum(0, 0), 0);'],['Используйте аргументы a и b.','Последним выражением может быть a + b.'],['Положительные числа','Отрицательные числа','Ноль'])
add('branches','foundations','Выбираем путь','if — это тоже выражение.','Ветвления возвращают значения','Условия if должны иметь тип bool. Ветки if и else могут возвращать значение: тогда их типы должны совпадать. Это позволяет писать компактно и не вводить изменяемую переменную.','pub fn sign(x: i32) -> &\'static str {\n    if x >= 0 { "неотрицательное" } else { "отрицательное" }\n}','Верните true, если age не меньше 18; иначе false. age — u8.','pub fn is_adult(age: u8) -> bool {\n    false\n}','pub fn is_adult(age: u8) -> bool { age >= 18 }',['assert!(is_adult(18));','assert!(!is_adult(17));','assert!(is_adult(99));'],['Не забудьте, что 18 лет уже подходит.','Сравнение age >= 18 само возвращает bool.'],['Граница 18','Меньше 18','Больше 18'])
add('loops','foundations','Повторение без рутины','Изменяемые переменные и диапазоны.','let mut и циклы','По умолчанию переменные неизменяемы. mut разрешает менять значение. for перебирает диапазон: 1..=n включает обе границы. При n = 0 диапазон 1..=0 для u32 пуст, поэтому сумма останется нулевой.','let mut total = 0;\nfor x in 1..=3 {\n    total += x;\n}','Верните сумму всех чисел от 1 до n включительно. n находится в диапазоне 0..=1000.','pub fn sum_to(n: u32) -> u32 {\n    let mut total = 0;\n    // Добавьте цикл\n    total\n}','pub fn sum_to(n: u32) -> u32 { let mut total=0; for x in 1..=n { total += x; } total }',['assert_eq!(sum_to(5), 15);','assert_eq!(sum_to(0), 0);','assert_eq!(sum_to(1), 1);'],['Понадобится диапазон с включённой верхней границей.','В цикле for x in 1..=n добавляйте x к total.'],['Сумма до 5','Пустой диапазон','Один элемент'])
add('borrow','ownership','Посмотреть, не забирая','Ссылки вместо перемещения.','Ownership и заимствование','У значения String один владелец. Передача String по значению перемещает владение, а &String или &str позволяет читать данные, не забирая их. Принимающий &str код работает и со строковыми литералами, и со String. chars() перебирает Unicode-символы; len() считает байты.','let name = String::from("Rust");\nlet view: &str = &name;\nprintln!("{view}");','Посчитайте количество Unicode-символов в строке. Для «ёж» результат 2, а не число байт.','pub fn char_count(text: &str) -> usize {\n    0\n}','pub fn char_count(text: &str) -> usize { text.chars().count() }',['assert_eq!(char_count("Rust"), 4);','assert_eq!(char_count("ёж"), 2);','assert_eq!(char_count(""), 0);'],['Не используйте text.len(): это количество байт.','Итератор text.chars() имеет метод count().'],['Латиница','Unicode','Пустая строка'])
add('mut-borrow','ownership','Меняем аккуратно','Одна изменяемая ссылка — одно место изменения.','Изменяемое заимствование','&mut String разрешает изменить строку без перемещения владения. В один момент времени допустима либо одна изменяемая ссылка, либо несколько неизменяемых ссылок на те же данные. push_str добавляет текст к строке.','let mut text = String::from("Rust");\nlet reference = &mut text;\nreference.push_str("!");','Добавьте ровно один «!» в конец переданной строки. Функция ничего не возвращает.','pub fn excite(text: &mut String) {\n    // Измените text\n}','pub fn excite(text: &mut String) { text.push_str("!"); }',['let mut s=String::from("Rust"); excite(&mut s); assert_eq!(s, "Rust!");','let mut s=String::new(); excite(&mut s); assert_eq!(s, "!");'],['Вам уже передали изменяемую ссылку.','Вызовите text.push_str("!").'],['Обычная строка','Пустая строка'])
add('owned-value','ownership','Создать и передать','Возвращаем собственные данные.','String владеет памятью','String — изменяемая строка в куче, которая владеет своими данными. &str — представление строки без владения. format! создаёт новый String, и при возврате владение переходит вызывающему коду. Нельзя вернуть ссылку на локальный String.','pub fn welcome(name: &str) -> String {\n    format!("Привет, {name}")\n}','Верните новый String: «Привет, ИМЯ!», подставив аргумент name.','pub fn welcome(name: &str) -> String {\n    String::new()\n}','pub fn welcome(name: &str) -> String { format!("Привет, {name}!") }',['assert_eq!(welcome("Миша"), "Привет, Миша!");','assert_eq!(welcome("Rust"), "Привет, Rust!");'],['Создайте новую строку через format!.','Внутри литерала format! можно использовать {name}.'],['Имя на кириллице','Имя на латинице'])
add('slice','ownership','Работаем с частью','Срезы без копирования.','Срез — вид на последовательность','&[i32] — ссылка на последовательность элементов, а не только на Vec. iter() читает элементы без перемещения. Метод sum() складывает числа, а тип результата определяется сигнатурой функции. Это пример абстракции без лишнего выделения памяти.','pub fn size(values: &[i32]) -> usize {\n    values.len()\n}','Сложите элементы среза. Пустой срез должен дать 0. Сумма гарантированно помещается в i32.','pub fn total(values: &[i32]) -> i32 {\n    0\n}','pub fn total(values: &[i32]) -> i32 { values.iter().sum() }',['assert_eq!(total(&[1,2,3]), 6);','assert_eq!(total(&[]), 0);','assert_eq!(total(&[-5,2]), -3);'],['Можно использовать цикл или iter().','values.iter().sum() возвращает нужную сумму.'],['Несколько чисел','Пустой срез','Отрицательные числа'])
add('option','collections','Значение может отсутствовать','Option вместо null.','Some и None','Option<T> явно описывает наличие или отсутствие значения. first() на срезе возвращает Option<&T>. copied() превращает ссылку на Copy-тип в собственное значение внутри Option, без unwrap и риска паники.','let numbers = [4, 8];\nlet first: Option<i32> = numbers.first().copied();','Верните первый элемент среза в Some. Если срез пуст, верните None. Не используйте unwrap.','pub fn first(values: &[i32]) -> Option<i32> {\n    None\n}','pub fn first(values: &[i32]) -> Option<i32> { values.first().copied() }',['assert_eq!(first(&[9,4]), Some(9));','assert_eq!(first(&[]), None);','assert_eq!(first(&[0]), Some(0));'],['У среза уже есть метод first().','После first() вызовите copied(), чтобы получить Option<i32>.'],['Первый элемент','Отсутствие значения','Ноль как значение'])
add('result','collections','Ошибка — тоже результат','Явно обрабатываем некорректный ввод.','Result<T, E>','Result содержит Ok(T) при успехе и Err(E) при ошибке. parse::<i32>() проверяет строку и возвращает Result. map_err позволяет привести ошибку к собственному понятному типу, не вызывая панику.','let number = "42".parse::<i32>();\nlet result = number.map_err(|_| "не число");','Преобразуйте text в i32. При любой ошибке возвращайте Err("не число"). Используйте стандартный parse, без обрезки пробелов.','pub fn parse_number(text: &str) -> Result<i32, &\'static str> {\n    Err("не число")\n}','pub fn parse_number(text: &str) -> Result<i32, &\'static str> { text.parse::<i32>().map_err(|_| "не число") }',['assert_eq!(parse_number("42"), Ok(42));','assert_eq!(parse_number("-7"), Ok(-7));','assert_eq!(parse_number("abc"), Err("не число"));','assert_eq!(parse_number("2147483648"), Err("не число"));'],['Сначала вызовите text.parse::<i32>().','Превратите ошибку в строку через map_err(|_| "не число").'],['Число','Отрицательное число','Неверный ввод','Переполнение'])
add('iterator','collections','Конвейер данных','filter → map → collect.','Итераторы ленивы','Итератор ничего не делает, пока его не потребляет завершающая операция вроде collect. filter выбирает элементы, map преобразует их. copied() позволяет удобно работать с числами вместо ссылок, сохраняя исходный срез.','let doubled: Vec<i32> = [1, 2, 3]\n    .iter().copied().map(|x| x * 2).collect();','Верните Vec квадратов только положительных чисел, сохранив порядок. Все входы от -1000 до 1000.','pub fn positive_squares(values: &[i32]) -> Vec<i32> {\n    Vec::new()\n}','pub fn positive_squares(values: &[i32]) -> Vec<i32> { values.iter().copied().filter(|x| *x > 0).map(|x| x*x).collect() }',['assert_eq!(positive_squares(&[-2,0,3,2]), vec![9,4]);','assert!(positive_squares(&[]).is_empty());','assert!(positive_squares(&[-1,0]).is_empty());'],['Сначала .iter().copied(), затем filter для x > 0.','После фильтра используйте map(|x| x * x).collect().'],['Фильтрация и порядок','Пустой ввод','Без положительных'])
add('hashmap','collections','Считаем слова','Ассоциативная коллекция и Entry API.','HashMap и entry','HashMap<K,V> хранит пары ключ-значение. entry(key).or_insert(0) даёт изменяемую ссылку на существующее значение или вставляет начальное. За счёт этого счётчик можно обновить без отдельного поиска. split_whitespace делит строку по пробельным символам.','use std::collections::HashMap;\nlet mut counts = HashMap::new();\n*counts.entry("Rust").or_insert(0) += 1;','Посчитайте частоту слов с учётом регистра. Возвращайте HashMap<String, usize>. Разделяйте слова через split_whitespace.','use std::collections::HashMap;\n\npub fn word_counts(text: &str) -> HashMap<String, usize> {\n    HashMap::new()\n}','use std::collections::HashMap; pub fn word_counts(text: &str) -> HashMap<String, usize> { let mut m=HashMap::new(); for w in text.split_whitespace() { *m.entry(w.to_owned()).or_insert(0) += 1; } m }',['let m=word_counts("rust rust code"); assert_eq!(m.get("rust"), Some(&2)); assert_eq!(m.get("code"), Some(&1));','assert!(word_counts("").is_empty());','assert_eq!(word_counts("Rust rust").len(), 2);'],['Создайте HashMap и пройдите по text.split_whitespace().','В цикле увеличивайте *map.entry(word.to_owned()).or_insert(0).'],['Повторения','Пустая строка','Учёт регистра'],12)
add('struct','design','Данные + поведение','Инкапсуляция через struct и impl.','Структуры и методы','struct объединяет данные, impl добавляет методы. self обозначает значение, &self — чтение без передачи владения. Приватные поля скрывают внутреннее устройство, публичные методы дают безопасный интерфейс. Это инкапсуляция без классов.','pub struct User {\n    name: String,\n}\nimpl User {\n    pub fn name(&self) -> &str { &self.name }\n}','Реализуйте Rectangle::area. Ширина и высота не больше 1000. Не меняйте структуру и new.','pub struct Rectangle {\n    width: u32,\n    height: u32,\n}\nimpl Rectangle {\n    pub fn new(width: u32, height: u32) -> Self {\n        Self { width, height }\n    }\n    pub fn area(&self) -> u32 {\n        0\n    }\n}','pub struct Rectangle { width:u32,height:u32 } impl Rectangle { pub fn new(width:u32,height:u32)->Self{Self{width,height}} pub fn area(&self)->u32{self.width*self.height} }',['assert_eq!(Rectangle::new(3,4).area(), 12);','assert_eq!(Rectangle::new(0,8).area(), 0);'],['Поля доступны через self.width и self.height.','Площадь — произведение ширины и высоты.'],['Площадь','Нулевая сторона'])
add('enum','design','Моделируем состояния','Невозможные состояния не представимы.','Enum и исчерпывающий match','Enum описывает набор возможных состояний. match требует обработать все варианты: добавили новый вариант — компилятор подскажет, где обновить логику. Вместо нескольких bool-полей, которые могут противоречить друг другу, используйте одно явное состояние.','enum Door { Open, Closed }\nfn open(door: Door) -> bool {\n    match door { Door::Open => true, Door::Closed => false }\n}','Верните названия состояний: Draft → «черновик», Running → «проверка», Passed → «готово».','pub enum Status { Draft, Running, Passed }\npub fn label(status: Status) -> &\'static str {\n    ""\n}','pub enum Status{Draft,Running,Passed} pub fn label(status:Status)->&\'static str { match status { Status::Draft=>"черновик",Status::Running=>"проверка",Status::Passed=>"готово" } }',['assert_eq!(label(Status::Draft), "черновик");','assert_eq!(label(Status::Running), "проверка");','assert_eq!(label(Status::Passed), "готово");'],['Используйте match status с тремя ветками.','Каждая ветка имеет вид Status::Draft => "черновик".'],['Draft','Running','Passed'])
add('trait','design','Общий контракт','Полиморфизм через traits.','Trait задаёт поведение','Trait похож на интерфейс: описывает возможности типа, а не его поля. impl Trait for Type связывает тип и контракт. Код, принимающий &impl Trait, работает с любым реализующим его типом: это статический полиморфизм без наследования.','pub trait Named { fn name(&self) -> &str; }\npub fn greet(value: &impl Named) -> String {\n    format!("Привет, {}", value.name())\n}','Реализуйте Score для Quiz: метод points возвращает correct * 10. correct не больше 1000.','pub trait Score {\n    fn points(&self) -> u32;\n}\npub struct Quiz { pub correct: u32 }\nimpl Score for Quiz {\n    fn points(&self) -> u32 {\n        0\n    }\n}','pub trait Score{fn points(&self)->u32;} pub struct Quiz{pub correct:u32} impl Score for Quiz{fn points(&self)->u32{self.correct*10}}',['assert_eq!(Quiz{correct:3}.points(), 30);','fn measure(s: &impl Score)->u32{s.points()} assert_eq!(measure(&Quiz{correct:2}),20);','assert_eq!(Quiz{correct:0}.points(), 0);'],['Число правильных ответов доступно через self.correct.','Верните self.correct * 10 из points.'],['Баллы','Вызов через trait','Ноль'])
add('composition','design','Маленький итоговый проект','Собираем знания в проверку решения.','Композиция вместо наследования','Композиция соединяет небольшие типы и функции. В Rust удобно явно представить успешный результат и ошибку через Result, а правила — через простые функции и traits. В этом задании используем struct, ссылки, Option и Result вместе.','pub struct Check { pub passed: bool }\nfn describe(check: &Check) -> &\'static str {\n    if check.passed { "готово" } else { "повторить" }\n}','Реализуйте average(scores): Err("пусто") для пустого среза, Err("балл вне диапазона") если хотя бы один балл больше 100, иначе Ok целочисленного среднего. Ограничение: не больше 1000 элементов. Сначала проверяйте пустой ввод.','pub fn average(scores: &[u32]) -> Result<u32, &\'static str> {\n    Err("пусто")\n}','pub fn average(scores:&[u32])->Result<u32,&\'static str>{ if scores.is_empty(){return Err("пусто");} if scores.iter().any(|x| *x>100){return Err("балл вне диапазона");} Ok(scores.iter().sum::<u32>() / scores.len() as u32) }',['assert_eq!(average(&[]), Err("пусто"));','assert_eq!(average(&[50,100]), Ok(75));','assert_eq!(average(&[101]), Err("балл вне диапазона"));','assert_eq!(average(&[0,1]), Ok(0));'],['Сначала is_empty(), затем any(|x| *x > 100).','Для корректного ввода разделите sum::<u32>() на scores.len() as u32.'],['Пустой ввод','Среднее','Недопустимый балл','Округление вниз'],15)
roadmap=[
 dict(title='05 / Lifetimes и generics',description='Ограничения типов, сложные заимствования, API библиотек.',outcome='Библиотека с документированным публичным API и тестами.'),
 dict(title='06 / Async и конкурентность',description='Tokio, Send/Sync, каналы, отмена, backpressure.',outcome='Очередь задач с корректным завершением и ограничением нагрузки.'),
 dict(title='07 / Backend и PostgreSQL',description='Axum, SQLx, миграции, транзакции, API и авторизация.',outcome='Многопользовательский REST API с тестами и OpenAPI.'),
 dict(title='08 / Инженерная практика',description='Архитектура, tracing, профилирование, CI, Docker и безопасность.',outcome='Развёрнутый сервис с метриками, бэкапами и runbook.'),
 dict(title='09 / Capstone + code review',description='Самостоятельный продукт, нагрузочные тесты и внешнее ревью.',outcome='Защищённый проект; оценка компетенций по рубрике, не автоматический титул middle.')]
(root/'backend/course.json').write_text(json.dumps(dict(modules=modules,lessons=lessons,roadmap=roadmap),ensure_ascii=False,indent=2))
print(f'Authored {len(lessons)} lessons, {len(modules)} modules, {len(roadmap)} planned modules')
