<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { useLearning } from '../store'
const store=useLearning(),search=ref(''),expanded=ref('')
const modules=computed(()=>store.course?.modules.filter(m=>m.track===store.selectedTrack) ?? [])
const lessonsIn=(id:string)=>store.trackLessons.filter(l=>l.module===id)
const doneIn=(id:string)=>lessonsIn(id).filter(l=>store.progress.completed.includes(l.id)).length
watch(()=>store.selectedTrack,()=>{search.value='';expanded.value=store.next?.module ?? modules.value[0]?.id ?? ''},{immediate:true})
const matches=computed(()=>store.trackLessons.filter(l=>(l.title+' '+l.summary+' '+l.outcome).toLocaleLowerCase().includes(search.value.toLocaleLowerCase().trim())))
</script>
<template><div class="page home">
 <section class="welcome-row"><div><span class="eyebrow">RUSTPATH / МАЛЕНЬКИЕ ШАГИ, НАСТОЯЩИЕ НАВЫКИ</span><h1>Код, который<br>вы понимаете.</h1><p class="lead">Выберите свой уровень. Разберите одну идею.<br>Закрепите её вопросом или работающим кодом.</p></div><div class="continue-card"><span class="eyebrow">{{ store.progress.completed.length ? 'ПРОДОЛЖИМ С ВАШЕГО МЕСТА' : 'НАЧНЁМ С ПОНЯТНОГО' }}</span><h2>{{ store.next?.title ?? 'Маршрут пройден!' }}</h2><p>{{ store.next?.summary ?? 'Повторите сложные темы или выберите следующий маршрут.' }}</p><div class="lesson-meta" v-if="store.next"><span>{{ store.next.kind==='quiz'?'Вопрос на понимание':'Практика с кодом' }}</span><span>{{ store.next.minutes }} мин</span></div><RouterLink v-if="store.next" class="primary" :to="`/learn/${store.next.id}`">{{ store.progress.completed.length ? 'Продолжить' : 'Первый урок' }} <span aria-hidden="true">→</span></RouterLink><RouterLink v-else class="primary" to="/review">Повторить изученное →</RouterLink></div></section>
 <section class="track-picker" aria-label="Ваш уровень"><button v-for="track in store.course?.tracks" :key="track.id" :class="['track-option',{selected:store.selectedTrack===track.id}]" :aria-pressed="store.selectedTrack===track.id" @click="store.selectTrack(track.id)"><span class="track-level">{{ track.level }}</span><strong>{{ track.title }}</strong><span>{{ track.description }}</span></button></section>
 <section class="course-region"><div class="course-heading"><div><span class="eyebrow">ВАШ МАРШРУТ</span><h2>{{ store.currentTrack?.title }}</h2><p>{{ store.completedTrack }} из {{ store.trackLessons.length }} уроков · {{ store.progress.xp }} XP всего</p></div><div class="course-search"><label for="lesson-search">Найти тему</label><input id="lesson-search" type="search" v-model="search" placeholder="Например, переменные"></div></div><div class="progress-track" role="progressbar" :aria-valuenow="store.percent" aria-valuemin="0" aria-valuemax="100" :aria-label="`Прогресс: ${store.currentTrack?.title}`"><span :style="{width:`${store.percent}%`}"></span></div>
 <div v-if="search.trim()" class="search-results"><p class="subtle">Найдено: {{ matches.length }} · поиск внутри выбранного маршрута</p><div v-for="lesson in matches" :key="lesson.id" class="search-result"><div><strong>{{ lesson.title }}</strong><p>{{ lesson.summary }}</p></div><RouterLink v-if="store.isUnlocked(lesson.id)" class="text-link" :to="`/learn/${lesson.id}`">Открыть →</RouterLink><span v-else class="subtle">Сначала предыдущий урок</span></div><div v-if="!matches.length" class="empty-state"><h3>Такой темы здесь нет</h3><p>Попробуйте другое слово или выберите другой маршрут.</p><button class="secondary" @click="search=''">Сбросить поиск</button></div></div>
 <div v-else class="module-stack"><article v-for="(module,i) in modules" :key="module.id" class="module"><button class="module-toggle" :aria-expanded="expanded===module.id" :aria-controls="`module-${module.id}`" @click="expanded=expanded===module.id?'':module.id"><span class="module-number">{{ String(i+1).padStart(2,'0') }}</span><span class="module-label"><strong>{{ module.title }}</strong><span>{{ module.description }}</span></span><span class="module-count">{{ doneIn(module.id) }}/{{ lessonsIn(module.id).length }}</span><span class="expand-icon" aria-hidden="true">{{ expanded===module.id?'−':'+' }}</span></button><div v-if="expanded===module.id" :id="`module-${module.id}`" class="module-body"><p class="module-outcome"><strong>После модуля:</strong> {{ module.outcome }}</p><ol class="lesson-list"><li v-for="(lesson,index) in lessonsIn(module.id)" :key="lesson.id"><RouterLink v-if="store.isUnlocked(lesson.id)" :to="`/learn/${lesson.id}`" :class="['lesson-row',{'lesson-current':store.next?.id===lesson.id}]"><span :class="['lesson-indicator',{complete:store.progress.completed.includes(lesson.id)}]">{{ store.progress.completed.includes(lesson.id)?'✓':index+1 }}</span><span class="lesson-title">{{ lesson.title }}<small>{{ lesson.kind==='quiz'?'Понимание':'Код' }} · {{ lesson.minutes }} мин · {{ lesson.xp }} XP</small></span><span class="lesson-action" aria-hidden="true">→</span></RouterLink><div v-else class="lesson-row locked"><span class="lesson-indicator">{{ index+1 }}</span><span class="lesson-title">{{ lesson.title }}<small>{{ lesson.minutes }} мин · {{ lesson.kind==='quiz'?'Понимание':'Код' }}</small></span><span class="lock-label">Позже</span></div></li></ol></div></article></div>
 </section><div class="home-bottom"><p><strong>Ошибки — часть обучения.</strong> Подсказки не отнимают опыт. Пройденные уроки доступны для повторения.</p><RouterLink to="/lab" class="text-link">Разобраться с ownership наглядно →</RouterLink></div>
 </div></template>
